config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Mock user_url that redirects to authenticated root because devise insists on using it as an after sign up redirect
  get "/users", to: redirect("/"), as: :user

  unauthenticated :user do
    root "home#index", as: :unauthenticated_root
  end

  authenticated :user do
    root "projects#index", as: :authenticated_root
  end

  get "/search", to: "search#index", as: :search

  resources :projects do
    # Since each task always belongs to a project
    resources :tasks, only: [:create, :update, :destroy, :edit, :new, :show]

    member do
      patch :move
    end
  end

  # But expose all tasks at /tasks as well (for the task list)
  resources :tasks, only: [:index]
  resources :tags, only: [:index, :new, :create, :destroy]
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  # Validations
  validates :title, presence: true
  validates :is_done, inclusion: { in: [true, false] }

  # Attachments
  attachment :file

  # Associations
  belongs_to :project
  belongs_to :user

  has_many :tags_tasks, class_name: "TagsTasks", dependent: :delete_all
  has_many :tags, through: :tags_tasks

  # Scopes
  include CommonScopes
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.where(user_id: current_user.id).includes(:project)

    if params[:query].present?
      @tasks = @tasks.search(params[:query])
    end

    if params[:scope].present? && params[:scope] != "all"
      @tasks = @tasks.where(is_done: params[:scope] == "done")
    end

    @pagy, @tasks = pagy(@tasks)
    @tags = Tag.left_joins(:tasks)
  end

  # GET /projects/xx/tasks/new
  def new
    @task = Task.new
    @project = Project.find_by(id: params[:project_id])
    @all_tags = Tag.where(user_id: current_user.id)
  end

  # POST /projects/xx/tasks
  def create
    # Check if project exists
    @project = Project.find_by(id: params[:project_id], user_id: current_user.id)
    if @project.nil?
      redirect_to projects_path, alert: t("projects.not_found")
      return
    end

    # Create the task
    @task = Task.create(task_params).tap do |t|
      t.project_id = @project.id
      t.user_id = current_user.id
    end

    if @task.save!
      # Update the tags
      unless params[:task][:tags].nil?
        set_tags(params[:task][:tags].to_a)
      end
      redirect_to project_path(params[:project_id]), notice: t(".success")
    else
      redirect_to project_path(params[:project_id]), alert: t(".failure")
    end
  end

  # GET /projects/xx/tasks/1
  def show
    # @task is already set by set_task
  end

  # GET /projects/xx/tasks/1/edit
  def edit
    # @task is already set by set_task
    @all_tags = Tag.where(user_id: current_user.id).to_a
    @checked_tags = TagsTasks.assigned_tags(@task.id)
  end

  # PATCH/PUT /projects/xx/tasks/1
  def update
    # @task is already set by set_task

    # Update the task
    if @task.update(task_params)
      # Update the tags
      unless params[:task][:tags].nil?
        set_tags(params[:task][:tags].to_a)
      end
      redirect_to project_path(params[:project_id]), notice: t(".success")
    else
      redirect_to project_path(params[:project_id]), alert: t(".failure")
    end
  end

  # DELETE /projects/xx/tasks/1
  def destroy
    # @task is already set by set_task
    if @task.destroy
      redirect_to project_path(params[:project_id]), notice: t(".success")
    else
      redirect_to project_path(params[:project_id]), alert: t(".failure")
    end
  end

  private
    # Automatically set the @task variable and redirect if not found
    def set_task
      @task = Task.where(id: params[:id], user_id: current_user.id).first
      redirect_to projects_path, alert: t(".not_found") if @task.nil?
    end

    # Filter the params
    def task_params
      params.require(:task).permit(:title, :description, :is_done, :tags, :file)
    end

    # Sets tags for a task while clearing the old ones
    # @param [Array] new_tags An array of tag ids
    def set_tags(new_tags)
      Task.transaction do
        @task.tags.clear
        new_tags.each do |tag|
          @task.tags << Tag.find_by(id: tag)
        end
      end
    end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/edit.html.slim
main style='max-width: 500px; margin: auto;'
  h1 =t('.title')
  = render 'partials/projects/form', url: project_task_path(@task.project, @task), submit_text: t('.save')

app/views/tasks/index.html.slim
main
  div style='display: flex; flex-direction: column; align-items: center;' class='mb-2'
    h1 = t('.title')
    = render 'partials/search_bar', search_path: tasks_path, placeholder: t('.search_placeholder')
    br
    = render 'partials/tasks/scopes', url: tasks_path
  table.table.table-striped
    thead
      tr
        th =t('.table.completed')
        th =t('.table.title')
        th =t('.table.description')
        th =t('.table.project')
        th =t('.table.tags')
        th =t('.table.actions')
    tbody
      - @tasks.each do |task|
        tr
          td= button_to project_task_path(task.project, task), method: :patch,
                        params: { task: { is_done: !task.is_done } }, class: 'btn btn-light',
                        title: task.is_done ? 'Mark as not done' : 'Mark as done' do
            = task.is_done ? '✔' : '❌'
          td= link_to highlight(task.title, params[:query]), project_task_path(task.project, task)
          td= task.description
          td= link_to task.project.title, task.project
          td
            - @tags.where(id: task.tag_ids).distinct.each do |tag|
              = link_to tag.title, '#', class: 'badge bg-info', style: 'margin-right: 5px;'
          td style='display: flex; gap: 10px;'
            = link_to t('shared.edit'), edit_project_task_path(task.project, task), class: 'btn btn-primary'
            = button_to t('shared.delete'), project_task_path(task.project, task), method: :delete,
                        form: { data: { turbo_confirm: t('shared.turbo_confirm') } }, class: 'btn btn-danger'

  div style='display: flex; justify-content: center; flex-direction: column; align-items: center;'
    == pagy_bootstrap_nav(@pagy)

app/views/tasks/new.html.slim
main style='max-width: 500px; margin: auto;'
  h1 ="#{t('.title')} #{@project.title}"
  = render 'partials/projects/form', url: project_tasks_url(@project), submit_text: t('.create')

app/views/tasks/show.html.slim
main style='display: flex; flex-direction: column; align-items: center;' class='mb-2'
  h1 style='text-align: center;' = @task.title

  = button_to project_task_path(@task.project, @task), method: :patch,
          params: { task: { is_done: !@task.is_done } }, class: 'btn btn-light',
          title: @task.is_done ? 'Mark as not done' : 'Mark as done' do
    = @task.is_done ? '✔' : '❌'
  div
    - @task.tags.each do |tag|
      = link_to tag.title, '#', class: 'badge bg-info', style: 'margin-right: 5px;'

  p = @task.description

  - if @task.file
    = link_to t('.download_file'), @task.file.url, class: 'btn btn-link'

  div.mt-2 style='display: flex; gap: 10px; width: 100%; justify-content: center;'
    = link_to t('shared.edit'), edit_project_task_path(@task.project, @task), class: 'btn btn-primary'
    = button_to t('shared.delete'), project_task_path(@task.project, @task), method: :delete,
              form: { data: { turbo_confirm: t('shared.turbo_confirm') } }, class: 'btn btn-danger'
    = link_to t('.create_new_task'), new_project_task_path(@task.project), class: 'btn btn-light'