config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Mock user_url that redirects to authenticated root because devise insists on using it as an after sign up redirect
  get "/users", to: redirect("/"), as: :user

  unauthenticated :user do
    root "home#index", as: :unauthenticated_root
  end

  authenticated :user do
    root "projects#index", as: :authenticated_root
  end

  get "/search", to: "search#index", as: :search

  resources :projects do
    # Since each task always belongs to a project
    resources :tasks, only: [:create, :update, :destroy, :edit, :new, :show]

    member do
      patch :move
    end
  end

  # But expose all tasks at /tasks as well (for the task list)
  resources :tasks, only: [:index]
  resources :tags, only: [:index, :new, :create, :destroy]
end

app/views/partials/_authenticated_nav.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li>
        <%= link_to t('nav.projects'), projects_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to t('nav.tasks'), tasks_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to t('nav.tags'), tags_path, class: "nav-link" %>
      </li>
      <li>
        <%= render 'partials/search_bar', search_path: search_path, placeholder: t('nav.search') %>
      </li>
    </ul>

    <div class="d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: "navbar-brand" do %>
            <%= image_tag "https://ui-avatars.com/api/?size=40&name=#{current_user.full_name}", alt: "Avatar", class: "rounded-pill" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to t('shared.logout'), destroy_user_session_path, class: "btn btn-outline-danger" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_common_form.html.slim
= simple_form_for model, data: { turbo: false }, url: url  do |f|
  = f.input :title
  = yield f
  = f.button :submit, submit_text, class: 'btn btn-primary mt-2'

app/views/partials/_search_bar.html.slim
= form_with url: search_path, method: :get, class: 'd-flex', local: true do |f|
  = f.text_field :query, class: 'form-control me-2', placeholder: placeholder, value: params[:query]
  = f.submit t('shared.search'), class: 'btn btn-outline-success'

app/views/partials/_unauthenticated_nav.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to t('nav.home'), unauthenticated_root_path, class: "navbar-brand" %>
    <div class="d-flex">
      <%= link_to t('shared.login'), new_user_session_path, class: "btn btn-primary" %>
    </div>
  </div>
</nav>