config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Mock user_url that redirects to authenticated root because devise insists on using it as an after sign up redirect
  get "/users", to: redirect("/"), as: :user

  unauthenticated :user do
    root "home#index", as: :unauthenticated_root
  end

  authenticated :user do
    root "projects#index", as: :authenticated_root
  end

  get "/search", to: "search#index", as: :search

  resources :projects do
    # Since each task always belongs to a project
    resources :tasks, only: [:create, :update, :destroy, :edit, :new, :show]

    member do
      patch :move
    end
  end

  # But expose all tasks at /tasks as well (for the task list)
  resources :tasks, only: [:index]
  resources :tags, only: [:index, :new, :create, :destroy]
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  after_destroy :update_positions_after_destroy
  before_validation :set_position, on: :create

  # Validations
  validates :title, presence: true
  validates :position, presence: true,
            numericality: { only_integer: true, greater_than: 0 }

  # Associations
  has_many :tasks, dependent: :destroy
  belongs_to :user

  # Scopes
  include CommonScopes

  # Methods

  # Get metrics about the project's tasks
  # @param user [User] The user
  # @return [Hash] The metrics
  # @example
  #  Project.tasks_metrics(user)
  # # => { 1 => { total_tasks: 3, completed_tasks: 1 }, 2 => { total_tasks: 2, completed_tasks: 0 } }
  def self.tasks_metrics(user)
    select("project.id AS project_id",
           "COUNT(task.id) AS total_tasks",
           "SUM(CASE WHEN task.is_done = true THEN 1 ELSE 0 END) AS completed_tasks")
      .from("projects AS project")
      .joins("LEFT JOIN tasks AS task ON task.project_id = project.id")
      .where("project.user_id = ?", user.id)
      .group("project.id")
      .index_by { |project| project.project_id }.to_h
  end

  # Changes the position of the project depending on the parameter
  # @param direction [String] The direction to move the project (up or down)
  # @example
  # project.move("up") # Moves the project up
  # project.move("down") # Moves the project down
  # project.move("invalid") # Does nothing
  # @see move_up
  # @see move_down
  def move_position(direction)
    if direction == "up"
      move_up
    elsif direction == "down"
      move_down
    end
  end

  private
    # Moves the project up. The position of the project is swapped with the previous project.
    def move_up
      # Execute as transaction to prevent unexpected behaviour
      Project.transaction do
        # Get the previous project
        previous_project = Project.where(user_id:).where("position < ?", position).order(position: :desc).first

        # Swap the positions
        if previous_project
          previous_project_position = previous_project.position
          previous_project.update(position:)

          update(position: previous_project_position)
        end
      end
    end

    # Moves the project down. The position of the project is swapped with the next project.
    def move_down
      # Execute as transaction to prevent unexpected behaviour
      Project.transaction do
        # Get the next project
        next_project = Project.where(user_id:).where("position > ?", position).order(:position).first

        # Swap the positions
        if next_project
          next_project_position = next_project.position
          next_project.update(position:)

          update(position: next_project_position)
        end
      end
    end

    # Set the position of the project to the last position + 1
    def set_position
      if position.nil?
        last_project = Project.where(user_id:).order(position: :desc).first
        self.position = last_project ? last_project.position + 1 : 1
      end
    end

    # Update positions of projects after a project that has been destroyed
    def update_positions_after_destroy
      Project.where(user_id: self.user.id).where("position > ?", self.position).update_all("position = position - 1")
    end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  # Validations
  validates :title, presence: true
  validates :is_done, inclusion: { in: [true, false] }

  # Attachments
  attachment :file

  # Associations
  belongs_to :project
  belongs_to :user

  has_many :tags_tasks, class_name: "TagsTasks", dependent: :delete_all
  has_many :tags, through: :tags_tasks

  # Scopes
  include CommonScopes
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :move]

  # GET / (authenticated)
  # GET /projects
  def index
    @projects = Project.where(user_id: current_user.id).order(:position)
    if params[:query].present?
      @projects = @projects.search(params[:query])
    end

    @pagy, @projects = pagy(@projects)
    # Get the project statuses
    @projects_tasks_metrics = Project.tasks_metrics(current_user)
  end

  # GET /projects/1
  def show
    # @project is already set by set_project
    @tags = Tag.for_tasks_in_project(@project)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    # @project is already set by set_project
  end

  # POST /projects
  def create
    @project = Project.new(title: project_params[:title], user_id: current_user.id)

    if @project.save!
      redirect_to projects_path, notice: t(".success")
    else
      redirect_to projects_path, alert: t(".failure")
    end
  end

  # PATCH/PUT /projects/1
  def update
    # @project is already set by set_project
    if @project.update(project_params)
      redirect_to projects_path, notice: t(".success")
    else
      redirect_to projects_path, alert: t(".failure")
    end
  end

  # PATCH /projects/1/move
  def move
    if @project.move_position(params[:direction].to_s)
      redirect_to projects_path, notice: t(".success")
    else
      redirect_to projects_path, alert: t(".failure")
    end
  end

  # DELETE /projects/1
  def destroy
    # @project is already set by set_project
    if @project.destroy
      redirect_to projects_url, notice: t(".success")
    else
      redirect_to projects_url, alert: t(".failure")
    end
  end

  private
    # Automatically set the @project variable and redirect if not found
    def set_project
      @project = Project.where(id: params[:id], user_id: current_user.id).first
      redirect_to projects_path, alert: t(".not_found") if @project.nil?
    end

    # Filter the parameters
    def project_params
      params.require(:project).permit(:title)
    end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  # Calculates percentage of finished tasks in a given projects (defined by it's metrics)
  # @param [Hash] project_metrics
  # @return [Float]
  # @example
  #  project_metrics = { "total_tasks" => 10, "completed_tasks" => 5 }
  # -> 50.0
  #  project_metrics = { "total_tasks" => 10, "completed_tasks" => 0 }
  # -> 0.0
  #  project_metrics = { "total_tasks" => 0, "completed_tasks" => 0 }
  # -> 0.0
  # @see Project#self.tasks_metrics
  def calculate_project_progress(project_metrics)
    return 0.0 if project_metrics[:total_tasks].zero?
    (project_metrics[:completed_tasks] / project_metrics[:total_tasks].to_f * 100).round
  end
end

app/views/projects/edit.html.slim
main style='max-width: 500px; margin: auto;'
  h1 =t('.title')
  = render 'partials/common_form', model: @project, url: project_url(@project), submit_text: t('.save')

app/views/projects/index.html.slim
main
  div style='display: flex; flex-direction: column; align-items: center;' class='mb-2'
    h1 =t('.title')
    = render 'partials/search_bar', search_path: projects_path, placeholder: t('.search_placeholder')
  table.table.table-striped
    thead
      tr
        th scope='col' =t('.table.position')
        th scope='col' =t('.table.title')
        th scope='col' =t('.table.status')
        th scope='col' =t('.table.percent_complete')
        th scope='col' =t('.table.actions')
    tbody
      - @projects.each do |project|
        tr
          td
            div style='display: flex; flex-direction: row; align-items: center;'
              = button_to "▲", move_project_url(project.id), params: { direction: 'up' },
                      method: :patch, class: 'btn btn-light', disabled: project.position == 1
              b style='margin: 0 10px;' = project.position
              = button_to "▼", move_project_url(project.id), params: { direction: 'down' },
                      method: :patch, class: 'btn btn-light', disabled: project.position == @projects.count
          td = link_to highlight(project.title, params[:query]), project_path(project)
          td
            = render partial: 'partials/projects/project_status', locals: { task_metrics: @projects_tasks_metrics[project.id]  }
          td
            = render partial: 'partials/projects/task_complete_bar', locals: { task_metrics: @projects_tasks_metrics[project.id] }
          td style='display: flex; gap: 10px;'
            = link_to t('shared.edit'), edit_project_path(project), class: 'btn btn-primary'
            = button_to t('shared.delete'), project_path(project), method: :delete,
                        form: { data: { turbo_confirm: t('shared.turbo_confirm') } }, class: 'btn btn-danger'

  div style='display: flex; justify-content: center; flex-direction: column; align-items: center;'
    == pagy_bootstrap_nav(@pagy)
    = link_to t('.new'), new_project_path, class: 'btn btn-primary'

app/views/projects/new.html.slim
main style='max-width: 500px; margin: auto;'
  h1 = t('.title')
  = render 'partials/common_form', model: @project, url: projects_url, submit_text: t('.create')

app/views/projects/show.html.slim
main style='display: flex; flex-direction: column; align-items: center;' class='mb-2'
  h1 style='text-align: center;' = @project.title

  table.table.table-striped
    thead
      tr
        th scope='col' = t('tasks.index.table.completed')
        th scope='col' = t('tasks.index.table.title')
        th scope='col' = t('tasks.index.table.description')
        th scope='col' = t('tasks.index.table.tags')
        th scope='col' = t('tasks.index.table.actions')
    tbody
      - @project.tasks.each do |task|
        tr
          td
            = button_to project_task_path(@project, task), method: :patch,
                        params: { task: { is_done: !task.is_done } }, class: 'btn btn-light',
                        title: task.is_done ? \
                                t('tasks.index.table.mark_as_incomplete') :\
                                t('tasks.index.table.mark_as_complete') do
              = task.is_done ? '✔' : '❌'
          td = link_to task.title, project_task_path(@project, task)
          td = task.description
          td.flex
            - @tags.where(id: task.tag_ids).distinct.each do |tag|
              = link_to tag.title, '#', class: 'badge bg-info', style: 'margin-right: 5px;'
          td style='display: flex; gap: 10px;'
            = link_to t('shared.edit'), edit_project_task_path(@project, task), class: 'btn btn-primary'
            = button_to t('shared.delete'), project_task_path(@project, task), method: :delete,
                      form: { data: { turbo_confirm: t('shared.turbo_confirm') } }, class: 'btn btn-danger'

  div style='display: flex; gap: 10px; width: 100%; justify-content: center;'
    = link_to t('.edit'), edit_project_path(@project), class: 'btn btn-primary'
    = link_to t('.new_task'), new_project_task_path(@project), class: 'btn btn-secondary'
    = button_to t('.delete'), project_path(@project), method: :delete,
                form: { data: { turbo_confirm: t('shared.turbo_confirm') } }, class: 'btn btn-danger'